# Generated by Django 4.2.6 on 2023-10-17 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SentimentApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentiment',
            old_name='Sentiment',
            new_name='sentiment',
        ),
    ]
